# Generated by Django 5.0.5 on 2024-05-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoption',
            name='can_buy',
            field=models.CharField(choices=[('yes', 'Yes'), ('rent only ', 'rent only')], max_length=100),
        ),
    ]
